### ISSUE TITLE
`dignode` command?

### ISSUE THREAD

**Issue by kiedtl** [BuckarooBanzay/digibuilder#14]
Having a way to remove nodes as well as placing them would be useful. I had assumed that one could simply `setnode` the node to be removed with default:air, but that doesn't seem to be the case.

To prevent this effect from being too good, it could have a longer delay (0.8 seconds?)

**Comment by SwissalpS** [comment]
I was thinking upgrades. A luaC, drawer controller or other logic unit to enable queries of inventory and drill or similar to enable digging.

One upgrade slot could suffice, to force player to decide which upgrade to use.

**Comment by SwissalpS** [comment]
The addition of ``dignode`` command would make it very easy for automatic farms.

I was going to add a quarry to dig the crops, but this would allow doing it with a single node that doesn't even require power.

Already as is it is a bit OP as building must use some form of energy and digging certainly would too.

Edit: using drill as upgrade, it would require user to charge it from time to time.
Other option is to allow it to use tools from inventory and dig/harvest that way.

**Comment by SwissalpS** [comment]
maybe it should be called ``dignode_with`` and user would have to specify with which tool to dig. This would allow filling buckets and cans too ;)

Just brain-dumping here, I'm still not sure a node called digibuilder should be able to dig at all.

**Comment by BuckarooBanzay** [comment]
+1 for digging nodes with the digibuilder, sounds like a useful addition

> maybe it should be called dignode_with and user would have to specify with which tool to dig

:+1: 

> but this would allow doing it with a single node that doesn't even require power.

Yeah, this is pretty OP, one possibility would be to require technic power to dig+place :thinking:

**Comment by kiedtl** [comment]
One possibility would be to have an upgrade slot that changes which commands are available, instead of merely adding commands. Example: no upgrade == get_node + set_node, lava pickaxe == dig_node, mithril chest == query_inventory. Perhaps even make a breaking change and gatekeep get_node behind a binocular upgrade.

Another idea: instead of unlimited digging, only allow removing nodes that were previously placed by the digibuilder, which would allow the digibuilder to use scaffolding and other temporary nodes while building without turning it into an OP quarry. I'm unsure how this can be implemented though, can digibuilder store custom metadata in nodes?

**Comment by SwissalpS** [comment]
> can digibuilder store custom metadata in nodes

technically it can, yes. This would complicate things hugely no matter how the tracking is done. One would have to consider that there are multiple digibuilders and each can be jumped around with the placed nodes or without them.

+1 to mithril chest
pickaxe would have to adapt to available mods, well all the upgrades would.
When technic is available, binoculars could be replaced with the prospector.

Edit: important to me is that the tools used to dig don't give xp but suffer wear and tear without uping their dig-counts. That's one reason the drill would be great. Another is that it already comes in three tiers allowing expansion of capabilities.

**Comment by kiedtl** [comment]
>  This would complicate things hugely no matter how the tracking is done. One would have to consider that there are multiple digibuilders and each can be jumped around with the placed nodes or without them.

Let me clarify: digibuilders would be able to dig any node that has been placed by a digibuilder. So, nodes would only need a single `_was_placed_by_digibuilder` bool -- not need to store the coords of the digibuilder or anything similar. Or am I misunderstanding?

**Comment by SwissalpS** [comment]
you are correct in most cases. Some nodes will change e.g. plants, pistons etc. and loose that marker.

**Comment by The4codeblocks** [comment]
nah
it's a digi*builder*, not a digi*digger*.

**Comment by kiedtl** [comment]
After some thought, I'm beginning to agree: limitations in these technic/mesecon nodes is what makes them interesting, and forces you to put them together like a puzzle to do complex things. In hindsight I may have been a bit hasty in making this suggestion (it was originally because I couldn't fit a quarry into a tight space I was working with).
