### ISSUE TITLE
inventory can't be filled via tubes

### ISSUE THREAD

**Issue by SwissalpS** [BuckarooBanzay/digibuilder#8]
it works with injectors but not tubes, is that intentionally?

**Comment by BuckarooBanzay** [comment]
This might be a bug:
https://github.com/BuckarooBanzay/digibuilder/blob/0166d3261ce7c78e5412f9f64a2de0ba5af11d5a/node.lua#L30

(i think i just copy+pasted that form a technic node)

Note to myself: add conditional tube-overlay too: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L8

**Comment by SwissalpS** [comment]
maybe add an expensive tube to recipe?
