### ISSUE TITLE
support for special nodes

### ISSUE THREAD

**Issue by SwissalpS** [BuckarooBanzay/digibuilder#9]
Are there any intentions to add support for special nodes like:
- cables
- tubes
- liquids (they work, when owning player is online, but buckets are destroyed)
- wires (mesecon/digiline)
- luac

or is that up to user to write translation code?
well, cable-plates are a very special one

**Comment by BuckarooBanzay** [comment]
Haven't gotten to that yet, i re-used most of the digtron placement code but left some hacky stuff out, supporting (almost) all placeable nodes was the plan, yes

**Comment by SwissalpS** [comment]
farming support for seeds would be huge ;)

We could make public farms where plants are replanted if visitors don't.

**Comment by BuckarooBanzay** [comment]
> farming support for seeds would be huge ;)

this should work now with: e900b8f695f68fb7d4eaf81603f6e87578d51774

cables and other items with custom `on_place` function _might_ work too, haven't tested them yet

**Comment by SwissalpS** [comment]
Cool will have to test.

**Comment by SwissalpS** [comment]
#11 addresses some of the mentioned bugs

**Comment by OgelGames** [comment]
Pipeworks deployers can place just about everything, why not copy those? Maybe you could also add the option to specify the placement direction in the digiline message? (for example seeds only work when placed downwards)

**Comment by SwissalpS** [comment]
> also add the option to specify the placement direction

yes, that is added:
https://github.com/SwissalpS/minetestDigibuilder/blob/0630181263820aa2ac86746d661c581ded28a53a/digiline.lua#L203 and subsequent lines

**Comment by SwissalpS** [comment]
> Pipeworks deployers can place just about everything

yes, but they too sometimes behave weirdly. Looking at code, it swaps over and under of pointed_thing.

When there is a node already in front of the deployer, and none two nodes away, the node is placed two nodes away. This is very similar to some of the weirdness encountered with digibuilder.

Thanks for the input, I'll continue my investigations, maybe the trick is with fake_player.

**Comment by SwissalpS** [comment]
seeds are working now :D (at least those I tried)

Also technic cans seem to work.

Edit: fake player needed an inventory for seeds to work.
